---
title: 'Muppet: program for simulating harvest control rules'
output:
  html_document: 
    keep_md: yes
    number_sections: yes
    toc_depth: 4
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: 4
date: "`r lubridate::now()`"
subtitle: Program description and instructions for users
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preamble

# Models and options

Following is a description of the features in the model.  Including more features is in many cases relatively simple, typical example is density dependent growth where the functional form will be variable between species.  Appendix ?? describes the models that have been set up an what special features are in each model.  

## Population model

### Propagation of stock in numbers

NOTE: Merge next two equations

\begin{equation}
\hat{N}{}_{0,y}=f\left(SSB_{y}\right)\label{stockeq:1}
\end{equation}


\begin{equation}
N_{0,y} = \hat{N}_{0,y}e^{\xi_{y}}\label{stockeq:2}
\end{equation}



\begin{equation}
N_{a+1,y+1}=N_{a,y}e^{-\left(F_{a,y}+M_{a,y}\right)}\label{stockeq:3}
\end{equation}

If the oldest age group is a plus group.  

\begin{equation}
N_{A,y+1}=N_{A-1,y-1}e^{-\left(F_{a,y}+M_{a,y}\right)}+N_{A,y-1}e^{-\left(F_{A,y-1}+M_{A,y-1}\right)}\label{stockeq:4}
\end{equation}


where A is the oldest age (plus group) in the bookkeeping system 




### Catches

NOTE: LOCATION OF SECTION MAY NOT BE APPROPRIATE


Catches removed from the stocks are derived from stock number by Baranov's equation. 

\begin{equation}
{C}_{a,y}=\frac{F_{a,y}}{Z_{a,y}}(1-e^{-Z_{a,y}})N_{a,y}\label{catcheq:1}
\end{equation}


The fishery is simulated as a single fleet modeled as a non-parametric separable model:

\begin{equation}
F_{a,y}=F_{y}S_{a,t}\label{catcheq:2}
\end{equation}

Where $t$ refers to time interval.  The simulation period is split into predetermined periods with fixed selection in each period.  


### Weights

The operating model uses three different weights:

* $cW_{a,y}$: Catch-weights at age
* $sW_{a,y}$: Stock-weights at age, often survey-weights
* $ssbW_{a,y}$: Weight of mature fish at age.

The average weights $\hat{W_{a,y}}$ are stochastically derived from mean historical weight at age based on user specified number of historical years:

Another option is to read the average weights $\hat{W_{a,y}}$ from a file.  The last year in the file is then used as average for the remaining years.  

\begin{equation}
W_{a,y}=\hat{W_{a,y}}e^{\sigma_{W}\xi_{w,y}}\label{eq:weighterr1}
\end{equation}

\begin{equation}
\xi_{w,y}=\left(\rho_{w}\xi_{w,y-1}+\sqrt{1-\rho_{w}^{2}}\varepsilon_{y}\right)\label{eq:weighterr2}
\end{equation}

\[
\varepsilon_{y}=N\left(0,1\right)
\]

where is 

* $\sigma_{w}$: The size of the variability in weights
* $\xi_{w}$: Autocorrelated noise generated by a $1^{st}$order AR model.

The error terms are user specified (input), the same error applied to all weights in a given year.

Another option available in the model is density dependent growth, the main problem there is to find sensible parameters for the model. This option has been used for 2 different stocks, mackerel and Icelandic haddock but the parametersation for is quite different for those two cases.  

Where density dependent growth is included catch and stock weights need to be linked and maturity might also be linked to mean weight at age.  (See section **).  

### Maturity

Maturity at age of can be either fixed or set as a function of of stock weights at age (this being stochastically derived, see above): The latter approach is used in the Icelandic haddock model (appendix **).  

$$m_{a,y} = \frac{1}{1+e^{\alpha_m+\beta_mlog(sW{a,y}))}}$$
where the parameters are established from historical data of maturity and stock weights.

Stochastic variability in maturity at age is not implemented.  

### Natural mortality

The natural mortality is an input to the model, being fixed for all years but can be different between agegroups.  A multiplier on natural mortality can be estimated and a multiplier on natural mortality of the oldest age group can also be estimated.  

### Spawning stock biomass

The spawning stock biomass is calculated as:

$$
SSB_{y}=\sum_{a}N_{a,y}ssbW_{a,y}p_{a,y}e^{(pM_{a}M_{a}+pF_{a}F_{a})}\label{eq:calcssb}
$$

where:

* $p_{a,y}$ is the proportion mature by age and year
* $ssbW_{a,y}$ is the weight at age of mature fish
* $pM_{a}$ proportion of natural mortality before spawning
* $pF_{a}$ proportion of fishing mortality before spawning.

### Recruitment

Recruitment can be modeled by any of seven different models.



**Beverton-Holt**:

\begin{equation}
R_y=R_{max}\frac{SSB_y}{SSB_y + \frac{SSB_{50}}{5}}
\label{ssb-r:eq5}
\end{equation}

$R_{max}$ is maximum recruitment and $\frac{SSB_{50}}{5}$ if spawning stock leading to 50\% of maximum recruitment.  

**Ricker**:

\begin{equation}
R_y=R_{max}\frac{e^1}{SSB_{max}}e^{\frac{-SSB_y}{SSB_{max}}}
\label{ssb-r:eq2}
\end{equation}


**Ricker with age as a covariate**:

\begin{equation}
R_y=R_{max}\frac{e^1}{SSB_{max}}e^{\frac{-SSB_y}{SSB_{max}}}e^{-a_{mean}}
\label{ssb-r:eq4}
\end{equation}

**Hockey-stick**:

\begin{equation}
R_{y}=min\left\{ R_{max},R_{max}\frac{SSB_{y}}{SSB_{break}}\right\}
\label{ssb-r:eq1}
\end{equation}

**Geometric mean**:

\begin{equation}
R_{y} = R_{max}
\label{ssb-r:eq0}
\end{equation}



In all the functions change in productivity at specified time can be estimated.  The change in productivity is multiplier on $R_{max}$ after the specified year.  


The recruitment is then generated from the spawning stock by:

\begin{equation}
N_{1,y+1}=f(SSB_{y})e^{\sigma_{R}\xi_{R,y}}
\end{equation}

\begin{equation}
\xi_{R,y}=\left(\rho_{R}\xi_{R,y-1}+\sqrt{1-\rho_{R}^{2}}\varepsilon_{y}\right)
\end{equation}


\[
\varepsilon_{y}=N\left(0,1\right)
\]

where here $f(SSB_{y})$ is one of the functions in equations \ref{ssb-r:eq0}
to \ref{ssb-r:eq5} and where:

* $\rho_{R}$: Is the cv of the recruitment 
* $\xi_{R,y}$: Autocorrelated noise generated by a $1^{st}$ order AR model.

$\sigma_R$ can be made a function of $SSB$ by the equation 

\begin{equation}
\sigma_R=\sigma_{R0}\times (\frac{SSB_{ref}}{SSB})^{\gamma_R}
\end{equation}

Where $\gamma$ is an estimated parameter, usually positive as relative variability in recruitment does more often increase with decreased stock size.   

[The parameters of the stock - recruitment functions as well as the variability $\sigma_{R}$,  autocorrelation $\rho_{R}$ and parameter relating stock size and relative variability $\gamma_R$  can be in the Historical assessment model and uncertainty in the estimates reflected in the values used in stochastic predictions. The recruitment error $\xi_{R,y}$ in stochastic simulations  is generated by a first order AR model

### Selection at age

Selection at age of the commercial fleet can be modelled by 3 different methods.  
* logit function $S_{a,y}=\frac{1}{1+e^{-\alpha\times(a-a_{50})}}$
* Estimating one number per age and selection - period up to specified maximum age beoynd which selection by age does not change.  
* Estimating selection as a function of on mean stock weights at age based on a logit function: $S_{a,y} = \frac{1}{1+e^{-\alpha(log(sW{a,y})-log(sW_{50})}}$.  Implemented for Icelandic haddock where mean weight at age can vary by nearly 2 years (age 6 in one year similar to age 4 in another year.  )

Uncertainty in selection can by included in $S_a = logit(\hat{S_a})+\xi_{S,y}$ where 

\begin{equation}
\xi_{S,y}=\left(\rho_{S}\xi_{S,y-1}+\sqrt{1-\rho_{S}^{2}}\varepsilon_{y}\right)
\end{equation}

Usually $\rho_{S}$ is relatively high meaning that changing in selection are slow.  



## VPA historical assessment

The program was initially conceived as a forward running historical assessment program.

The model can also be used in reverse mode, estimating the survivors
in the beginning of the assessment year calculating backwards using
Popes approximation..  

\begin{equation}
N_{a,y}=N_{a+1,y+1}(e^{\frac{M_{a,y}}{2}}+C_{a,y})e^{\frac{M_{a,y}}{2}}\label{reveq:1}
\end{equation}

As usually for VPA model with assumptions about the oldest age are a problem, especially if it is a plus group.  For this model the forward model writes out $N$ of the oldest and second oldest  age group, that are  then used in the backward model.  If the oldest age group is a plus group both the oldest and second oldest age groups from the separable model are used but else only the oldest age group.  Running the model in reverse mode requires only one number changed in one input file.    

### Objective functions

#### Catch at age

The error in the catch at age is assumed to be log-normal and hence
the likelihood is calculated as:

\begin{equation}
L_{C}=\sum_{y}\sum_{a}\left\{ \frac{\left(log\left[C_{a,y}+\epsilon_{C}\right]-log\left[\hat{C}_{a,y}+\epsilon_{C}\right]\right)^{2}}{2\sigma_{aC}^{2}}+log\left(\sigma_{aC}\right)\right\} 
\end{equation}


where $\epsilon_{C}$ is to reduce the effect of very small catches
that are poorly sampled. Typical value of $\epsilon_{c}$would be
catches corresponding to 2-4 sampled otoliths. The standard deviations
$\sigma_{aC}$ are estimated as a multiplier on prespecified pattern
with age. The pattern was obtained as residuals from a separable run
using one separably period. 

The selection of the $\epsilon_{C}$ parameter is very important for stocks like 
the Norwegian spring spawning herring where contrast in year-class strength is
large and too small value of $\epsilon_{C}$ will cause low values
where sampling error starts to dominate to have too high value.  The
same consideration applies to survey indices as described below. In
the model   $\epsilon_{C}$  is given as proportions that is then
proportion of total catch in numbers.  

#### Total landings

As described above catch in numbers at age is one component in the
objective function to be minimized. This does in many cases guarantee
that the modeled catch in tonnes is close to the landed catch but
in some years this is not the case. In all cases one has:

\begin{equation}
Y_{y}=\sum_{a}C_{a,y}cW_{a,y}
\end{equation}


\begin{equation}
\hat{Y}_{y}=\sum_{a}\hat{C}_{a,y}cW_{a,y}\label{catcheq:5}
\end{equation}


To let the model follow the ``real'' landed catch the following
term is added to the objective function.

\begin{equation}
L_{Y}=\sum_{y}\left[\frac{\left(logY_{y}-log\hat{Y}_{y}\right)^{2}}{2\sigma_{Y}^{2}}+log\sigma_{Y}\right]
\end{equation}


Where $\sigma_{Y}$ is input from a file and was set to 0.1.  
The statistical properties of this term as an addition
to catch at age are somewhat questionable, but this formulation has
often been used in statistical catch at age models. 


#### Survey at age

The predicted survey index $\hat{I}_{ay}$ is calculated from:

\begin{equation}
\hat{I}_{a,y}=\alpha_{a}N_{a,y}^{\beta_a}
\end{equation}



where $\alpha_{a}$  are estimated parameters while $\beta_a$ was set
to one for the herring. The error
in the survey at age is assumed to be log-normal and hence the likelihood
is calculated as:

\begin{equation}
L_{I}=\sum_{y}\sum_{a}\left\{
  \frac{\left(log\left[I_{a,y}+\epsilon_{I}\right]-log\left[\hat{I}_{a,y}+\epsilon_{I}\right]\right)^{2}}{2\sigma_{aI}^{2}}+log\left(\sigma_{aI}\right)\right\} 
\label{eq:surnocorr}
\end{equation}


where $\epsilon_{I}$ is externally set and is to reduce the effect
of very small survey indices that are poorly sampled. Typical value
of $\epsilon_{I}$ would be indices that correspond to 2-4 sampled
otoliths. As described above for the catch likelihood this term very
important in this stock where contrast in year-class size is large.  

For the spring spawning herring correlation between indices of 
different age groups in the same year is modeled and  equation
\ref{eq:surnocorr} changes to:

\begin{equation}
{\bf
  \Gamma}=log\left[I_{a,y}+\epsilon_{I}\right]-log\left[\hat{I}_{a,y}+\epsilon_{I}\right]
\label{eq:surcorr1}
\end{equation}


\begin{equation}
L_{I}=\sum_{y}\left\{ 0.5log\left(det\Theta_{I}\right)+{\bf
    \Gamma}^{T}\Theta_{I}^{-1}\Gamma\right\} 
\label{eq:surcorr2}
\end{equation}


In the model runs conducted here the matrix ${\bf \Theta_{I}}$ is
generated by a 1st order AR model 

\begin{equation}
\Theta_{Iij}=\sigma_{2i}\sigma_{2j}\kappa^{abs(i-j)}
\end{equation}


where$\kappa$ is an estimated parameter which has been estimated
in the range $0.5$ to $0.5$ for the spring spawning herring in the May
survey (survey 5).  High value of $\kappa$ indicates that the residuals
in the survey approach a year factor while  with $\kappa=0$ equation 
\ref{eq:surcorr2} becomes identical to equation \ref{eq:surnocorr}.  

The standard deviations $\sigma_{aI}$
are estimated by the model by giving the pattern, estimating an multiplier.
The pattern can for example be estimated in an Adapt type model 
and thereafter smoothed. 

Survey 4 in the Barents sea does only take 2 age-groups (age 1 and 2)
and correlation of residuals is not modeled there.  

If there is more than one survey in the model the total survey likelihood is 

\begin{equation}
L_I = sum_{i=1}^{i=N_s} W_i L_{I_i}
\end{equation}

#### Stock-recruitment

This component involves discrepancy between observed and modeled
recruitment. The model allows for auto-correlation in residuals and
CV of residuals can be a function of spawning stock size. The likelihood
is calculated by the equations. 

\begin{equation}
\hat{N}{}_{0,y}=f\left(SSB_{y}\right)\label{eq:ssb}
\end{equation}


\begin{equation}
{\bf \Gamma_{SSB-R}}=log\left[N_{0,y}\right]-log\left[\hat{N}_{0,y}\right]
\end{equation}


\begin{equation}
\sigma_{3y}=\sigma_{3}\left(\frac{{SSB_{y}}}{SSB_{ref}}\right)^{\beta_{3}}\label{eq:cvvsssb}
\end{equation}


\begin{equation}
\Theta_{SSB-Rij}=\sigma_{3i}\sigma_{3j}\kappa_{3}^{abs(i-j)}
\end{equation}


\begin{equation}
L_{SSB-R}=\sum_{y}\left\{ 0.5log\left(det\Theta_{SSB-R}\right)+{\bf \Gamma_{SSB-R}^{^{T}}}\Theta_{SSB-R}^{-1}\Gamma_{SSB-R}\right\} 
\end{equation}


The parameters $\sigma_{3}$,$\kappa_{3}$and $\beta_{3}$are all
among estimated parameters but estimating them all in addition to
the 2 parameters of the SSB-rec function caused some difficulty so
$\kappa_{3}$and $\beta_{3}$were set to zero in the estimation part
but a fixed value of the auto-correlation parameter, estimated external
to the model used in the stochastic simulations. 

The choice of stock recruitment function has minor effect on the results
of stock assessment but is very important in future simulations. Estimation
of more than two one parameter ( usually $R_{max}$ and  $\sigma_{3}$ are
estimated) leads to very little improvement of the likelihood
function. Addition of the 3rd parameter ($SSB_{break}$) is on the
other hand important in stochastic simulations where the stock recruitment and
the the uncertainty in the stock recruitment function start to
matter.  

One more parameter that can be estimated in the model is sudden change
in productivity at certain time interval.  This parameters might be
used around the collapse as the selection pattern of the fisheries
before and after the collapse is extremely different making relative
estimated recruitment dependent on the level of M used for age 0-2. 


#### The full likelihood

The most important likelihood components have be described above.  There are in additions few other components that are not used very much but would rather be called constraints.     

The total objective function to be minimised is the weighted sum of the log-likelihood values.  

\begin{equation}
L_{tot}= W_C L_C W_{SSB-R} L{SSB-R} + W_I L_{I} + +W_Y L_{Y}
\end{equation}



### Estimated parameters

NOTE: LOCATION OF SECTION MAY NOT BE APPROPRIATE

\begin{description}
\item [{Estimated}] parameters in the assessment model are\end{description}
\begin{itemize}
\item Initial numbers in stock. 
\item Recruitment at age 0  each year
\item Parameters of the stock - recruitment function, $SSB_{break}$,
  $R_{max}$ and is $\sigma_{3}$.  
\item Selection pattern of the fisheries.
\item Fishing effort each year. 
\item $q_{a}$for the surveys
\item $\sigma_{c}$ and  $\sigma_{I}$ for each survey.  
\item Correlation parameter $\kappa_{I}$ in the survey likelihood.
\end{itemize}

The estimation of some of those parameters can be turned off and
initial values given used.  Among those parameters are all the
SSB-recruitment parameters and the $\kappa_{I}$ parameter in the
survey likelihood.  

As described in the beginning the inverse Hessian matrix of the parameter
estimates is used as a proposal distribution in MCMC runs. The number
of runs was usually 2 million with the parameter set from every 1000th
run saved. Probability distribution of spawning stock, total biomass  biomass
and other parameters is obtained by printing the respective values
to a file in each of the stochastic simulations. 

The exact settings of the historical assessment model do affect the
estimate of stock in the assessment year ($\pm16\%$) but have less
effect on the results of the long term simulation where the stock-recruitment
parameters have most effect while they have minor effect on the estimate
of the stock in the assessment year. If the simulation were run in
a closed loop with assessment model in the feedback loop those settings
would have more effect, but to use it to infer about ``correct''
model settings would require a realistic observation model. 


#Future simulations.  

## Setting of stochastic terms.  

The model is first run in optimizing mode where parameters are estimated and short term deterministic projections done.  The next step is to run mcmc simulations and save parameters for stochastic simulations.  The stochastic simulations are dependent on a number of random sequences being generated.  

\begin{itemize}
\item  Stochastic recruitment.  Generated from the estimated parameters of the stock-recruitment function.  If $\rho_{R}$ is estimated the sequence of estimated values is used to generate the random sequence, else it is specified in a file.  

\item  Assessment error, autocorrelated lognormal with $\sigma_A$, $\rho_A$, and bias  $\beta_A$ specified.  The bias specified is in addition to the lognormal bias.  The assessment error does usually apply to stock biomass in the assessment year.  The same relative error on all agegroup is assumed, something that could be improved as often the uncertainty is more in the recruiting age groups.  Uncertainty of different age groups is in reality not completely correlated as used here, recruiting age groups are often uncorrelated with the fishable stock.  

Usually 

\item Stochasticiy in mean weight at age is described in section **.

\item Stochasticity in selection and maturity at age is currently not in the model.  

\end{itemize}

Each stochastic iteration and sequence starts with a different seed. This means to take an example that recruitment residuals, assessment error and stochasticity in mean weight at age are independent.    Running the model again will on the other hand lead to exactly the same random sequence being repeated to runs with different harvest rate can be compared iteration by iteration.   

## Initial numbers for simulations.  

The transfer from assessment to simulations is somewhat tricky, which cohorts are estimated has to be specified, starting values of assessment error specified and "correct uncertainty" in the stock abundance in the beginning of the assessment year specified.   Assessment year is here the year after the last catch at age data.  Often one or more surveys are available in the assessment year.  HCR evaluation done in the model are based on assessment done in certain year, referred here as the first simulation year.  

The historical assessment (see section xxx) gives a probability distribution of the total biomass, spawning stock and other values in the beginning of the first simulation  year. The standard deviation of these probability distributions is often lower than than assessment error obtained by other means (e.g. historical retrospective analysis). 


To make the assessment error in the first year comparable with that used in the simulations, the stock numbers in the beginning of the assessment year are 

\begin{equation}
N_{assyr,a}=N_{assyr,a}e^{\sigma_{A}rat_{y}\epsilon}
\end{equation}

where $\varepsilon=N\left(0,1\right)$. The value set for the $rat_{y}$ is determined such that the probability distribution of reference biomass has similar standard error as obtained from the analysis leading to specification of the assessment error ($\sigma_A$). All variability in stock size in the beginning of the assessment year is anyway caused by assessment error. $rat{y}=1$ would lead to too much variability in the first simulation year as the assessment error is added to stock numbers that do already have some variability.  Typical value of the parameter $rat_{y}$ range from 0.3-0.8.  

The point estimate of the spawning stock size from the most recent assessment is one of the inputs to the prediction and the first value of the assessment error  is set as the log-ratio of that value and the spawning stock biomass in each stochastic run. If the stock is small the assessment is an overestimate, leading possibly to still further depletion of the stock. The sequence of values $\xi_{y}i$ in equation \ref{eq:asserr2} which starts in the assessment-year is obtained by the equation. 

\begin{equation}
\xi_{assyear}=log(\frac{SSB_{R.assessment}}{SSB_{R.simulation}})\frac{}{\sigma_{A}}
\end{equation}


Where $SSB_{R.assessment}$is the spawning stock  biomass from the assessment and $SSB_{R.simulation}$ spawning stock  biomass from the simulation, different value in each stochastic simulation. 

One of the factors leading to underestimate of uncertainty in assessment is ignored positive correlation in measurements, both between age-groups in a survey in the same year, between adjacent years and when the assessment is tuned with more than one survey, treated as independent.   


Starting values stochasticity in mean weight at age are random and not linked to past values even though the weights are multiplied by an autocorrelated year factor.  There is some flexibility in how the weights and maturity  in the short term are specified as they can be read from a file and last year in the file becomes the basis for future weights.  

Autocorrelated recruiment residuals are generated based on estimated or specified characteristics of the residuals.  The first recruitment that is not estimated is not linked to earlier recruitment, doing so could be somewhat tricky but not impossible.  Could be needed if the simulation start following a long sequence of poor recruitment.  A fix that will be implemented is to specify the average of the first recruitment residual in the prognosis file.  


## Observation model

Two^[An additional module (not available in this version) is a decision model based on survey biomass.] observation models are currently available:

* Biomass model: used in the decision model based on harvest rates.
* Stock-in-numbers model: used in decision models based on instantaneous fishing mortality.

In both cases the target exploitation rate in the decision model are often a function of some biomass (i.e. $B_{trigger}$), these being derived slightly differently in the observation model.

Ordinarily three parameters are required in an observation model: the standard deviation (input as cv), the 1st order auto-correlation and the bias. 



#### Biomass in the assessment year

The observation model is derived from the population model by applying user specified error terms on some reference biomass in the assessment year:


\begin{equation}
B_{R,y}=f({N}_{a,y}) \\ 
\widetilde{N}_{a,y}=N_{a,y}e^{CV_{A}\xi_{y}}e^{\beta_A}\label{eq:asserr1a} \\ 
\widetilde{B}_{R,y}=f(\widetilde{N}_{a,y}) 
\end{equation}

where $\widetilde{B}_{R,y}$ is the observed reference biomass, $B_{R,y}$ is the true reference biomass, $CV_{A}$ is the CV of the assessment error, $\beta_A$ bias in the assessment error (in addition to the lognormal bias) and $\xi_{y}$ the correlated error term   generated by the first order AR model^[$\rho_{A}$. 

\begin{equation}
\xi_{y}=\left(\rho_{A}\xi_{y-1}+\sqrt{1-\rho_{A}^{2}}\varepsilon\right)\label{eq:asserr2a}
\end{equation}

where $\varepsilon=N\left(0,1\right)$. The spawning biomass in the observation model is equivalently calculated as:

\begin{equation}
SSB_y = g(N) \\ 
\widetilde{SSB}_{y}=g(\widetilde{N}_{a,y})\label{eq:asserr3a} \\
\end{equation}

Same error values and structure through time are applied to both measures of biomass, i.e. within a year both biomasses are under- or overestimated by the equivalent amount.  

If the biomasses are based on catch weights uncertainty in estimation of weights is added.  If survey weights in the beginning of the year are available this uncertainty is relatively small.  

If spawning stock does not apply to the beginning of the year fishing mortality from last year is used to project the stock to spawning time.  

#### Biomass in the advisory year

The observation model is derived from the population model by applying user specified error terms on the true stock-in-numbers at age:

\begin{equation}
\widetilde{N}_{a,y}=N_{a,y}e^{CV_{A}\xi_{y}}e^{\beta_A}\label{eq:asserr1}
\end{equation}

where $\widetilde{N}_{a,y}$ are the observed stock-in-numbers, $N_{a,y}$ is the true stock in numbers, $CV_{A}$ is the CV of the assessment error and $\xi_{y}$ the correlated error term   generated by the first order AR model^[$\rho_{A}$: Need to define/derive]:

\begin{equation}
\xi_{y}=\left(\rho_{A}\xi_{y-1}+\sqrt{1-\rho_{A}^{2}}\varepsilon\right)\label{eq:asserr2}
\end{equation}


The stock is projected through the assessment years by assuming that $\widetilde{cW}_{a,y} = cW_{a,y-1}$ and $\widetilde{sel}_{a,y} = sel_{a,y-1}$.  The uncertainty in prediction of weight at age is to assume it is unchanged.  

\begin{equation}
\widetilde{N}_{y+1}=f\left(\widetilde{N}_{a,y},\widetilde{cW}_{a,y},sel_{y},TAC_{y}\right)\label{eq:asserr3}
\end{equation}

Where $\widetilde{cW}_{a,y}$ are predicted weights at age and the $TAC_{y}$ is the catch in the assessment year, having been estimated in the Decision model one year earlier. The equation is solved numerically by bisection method. 

The predicted weight and the maturity values in the framework could be derived from some average past values, the number of years used in the calculation of the average based on user specified input. If simply using last years values as done currently in the model one has:

\begin{eqnarray}
\widetilde{cW}_{a,y+1} = \widetilde{cW}_{a,y} = cW_{a,y-1}  \\
\widetilde{sW}_{a,y+1} = \widetilde{sW}_{a,y} = sW_{a,y-1}  \\
\widetilde{pM}_{a,y+1} = \widetilde{pM}_{a,y} = pM_{a,y-1} \\
\widetilde{sel}_{a,y+1} = \widetilde{sel}_{a,y} = sel_{a,y-1} \\
\widetilde{ssbW}_{a,y+1} = \widetilde{ssbW}_{a,y} = ssbW_{a,y-1} \label{eq:wtpred}
\end{eqnarray}

Here $sel_{a,y-1}$ is poorly estimated but does luckily have minor effect is TAC is compiledd based on fixed selection pattern.  

If spawning stock does not apply to the beginning of the year fishing mortality from last year before the assessment year is used to project the stock to spawning time. 

### Stock-in-numbers model (F-rules)

Last section demonstrated how the stock was projected to the beginning of the advisory year.  The predictions of biological parameters are shown in equation \ref{eq:wtpred}.  The prediction needed for a F rule are mostly the same as for biomass in the advisory year.  The main difference is more need to predict selection reliably.  





## Decision model


The model has at the moment the following desicion rules.  

1. Fixed catch (TAC), no stabilizer
2. F rule. TAC/Catch constraint in the first (assessment) year, F there after. F implemented as multiplier.  No reduction below $B_{trigger}$.  Mostly for assessment mode.  
3. HR rule based on biomass in the assessment. 
4. HR rule based on biomass in the advisory year.
5. F rule. TAC/Catch constraint in the first and future assessment years (although TAC for each year is based on F).
6. F rule in all years. F implemented as multiplier.  No reduction below $B_{trigger}$.  Mostly for assessment mode.  

Rules 1,2 and 6 are used in the assessment phase to perform assessment and short term prediction.  Rules 3,4 and 5 are for HCR evaluations, all based on applying specified assessment error to the stock in the beginning of the assessment year.  


### Biomass model i.e rules 3 and 4 in the list above.  

The model has a number of biomass rules where the TAC next year is a function of a reference biomass $B_R$ and trigger biomass ($B_T$).  The trigger biomass is most often the spawning stock but can be something else for example in stocks where maturity is highly variable or not available at the time of assessment.  In the text below the trigger biomass is always called SSB.  

The biomass rules do all have the option of stabiliser where the TAC is the average of last years TAC and the TAC according toe the biomass rule.  The stabiliser can be turned off suddenly below $B_{trigger}$ (not implemented at the moment) or gradually.  

There are 3 types of reference biomass.  


\begin{itemize}
\item Biomass above certain age based on stock weights.  
\item Biomass above certain age based on catch weights.  
\item Biomass above certain size based on stock weights.  
\end{itemize}

Biomass based on some "selection curve" as function of age will later be added. Biomass above certain size is implemented as logit function in terms of stock weights (parameters defined for Icelandic Haddock) but could easlily be adapted for other stocks.  

In all the biomass models it needs to be specified if the TAC is for and Icelandic fishing year (September 1st in the assessment year till August 31st next year) or the calendar year following the assessment year.  When using the fishing year $\frac{1}{3}$ of the TAC is caught in the assessment year and $\frac{2}{3}$ in the following year.  When basing TAC for Icelandic fishing year is compiled based on reference biomass in the advisory year


The steps shown here are the same for rules based on biomass in the advisory year and assessment year.  

The first step is to compile  reference biomass which is usually the basis of advice and then $B_{proxy}$ that does not affect the advice unless $B_{proxy}$ is estimated below $B_{trigger}$.  

Example of reference biomass are.  

#### Icelandic saithe 

Biomass 4+ in the assessment year based on catch weights.  $B_{proxy}=SSB$

\begin{equation}
\widetilde{B}_{R, y}=\sum_{a=4}(\widetilde{N}_{a,y},\widetilde{cW}_{a,y}) \\
\widetilde{SSB}_{y}=\sum_{a=4}\widetilde{N}_{a,y}e^{pM M_{y,a}+pF F_{y-1,a}}
\widetilde{ssbW}_{a,y+1}\widetilde{p}_{a,y+1}\label{eq:calcsaithe} \\
\end{equation}

#### Icelandic haddock

45cm and larger in the advisory year.  Converted to a logit function in terms of stock weights $sW$.  


\begin{equation}
\widetilde{B}_{R, y+1}=\sum_{a}\widetilde{N}_{a,y+1}\widetilde{sW}_{a,y} f1(\widetilde{sW}_{a,y}) \\ 
f1(x) = \frac{1}{(1+e^{-25.224-5.307 log(\frac{x}{44.5^3}})}
\label{eq:calcbtmp}
\end{equation}

where $\widetilde{sW}_{a,y+1}$ is the predicted stock weight at age. This rather strange formula is a proxy for the biomass of 45+cm and larger haddock.  

Predicted spawning stock in the advisory year is.  

\begin{equation}
\widetilde{SSB}_{y+1}=\sum_{a}\widetilde{N}_{a,y+1}\widetilde{ssbW}_{a,y+1}\widetilde{p}_{a,y+1}\label{eq:calcssbtmp1}
\end{equation}

where $\widetilde{ssbW}_{a,y+1}$ is the predicted spawning stock weight and $\widetilde{p}_{a,y+1}$ the predicted maturity at age.  

#### Stabilisers.  

When the reference biomass has been compiled the advice can be compiled in 5 different ways , with and without stabilisers and how they are turned on and off at $B_{trigger}$

Rule 0:
\begin{equation}
TAC_{y/y+1}=\alpha\tilde{B}_{4+,y}
\label{eq:rule0}
\end{equation}
Rule 1:
\begin{equation}
TAC_{y/y+1}=\alpha min\left\{ 1,\frac{\widetilde{SSB}_{y}}{B_{trigger}}\right\} \tilde{B}_{4+,y}
\label{eq:rule1}
\end{equation}
Rule 2:
\begin{equation}
TAC_{y/y+1}=(1-\beta)\alpha min\left\{ 1,\frac{\widetilde{SSB}_{y}}{B_{trigger}}\right\} \tilde{B}_{4+,y}+\beta TAC_{y-1/y}
\label{eq:rule2}
\end{equation}
Rule 3:
\begin{equation}
\begin{array}{cc}
TAC_{y/y+1}=(1\text{-}\beta)\alpha\tilde{B}_{4+,y}+\beta TAC_{y-1/y} & \widetilde{SSB}_{y}\geq B_{trigger}\\
TAC_{y/y+1}= \alpha\tilde{B}_{4+,y} & \widetilde{SSB}<B_{trigger}
\end{array}
\label{eq:rule3}
\end{equation}
Rule 4:
\begin{equation}
\begin{array}{cc}
TAC_{y/y+1}=(1\text{-}\beta)\alpha\tilde{B}_{4+,y}+\beta TAC_{y-1/y} & \widetilde{SSB}_{y}\geq B_{trigger}\\
TAC_{y/y+1}=(1\text{-}\beta\frac{\widetilde{SSB}_{y}}{B_{trigger}})\alpha\frac{\widetilde{SSB}_{y}}{B_{trigger}}\tilde{B}_{4+,y}+\beta\frac{\widetilde{SSB}_{y}}{B_{trigger}}TAC_{y-1/y} & \widetilde{SSB}<B_{trigger}
\end{array}
\label{eq:rule4}
\end{equation}


where $y$ refers to the assessment year, $y/y+1$ refers to the fishing year, starting September 1 in year $y$ and ending 31 August in year $y+1$. The value of the reference and spawning biomass are based on the spring assessment in year $y$. In the proposed HCR $\beta=0.50$, $\alpha=0.20$ and $B_{trigger}=65 kt$. Rule 3 is according to the formal request but Rule 4, which implies a smoother transition of the weights of the stabilizer if the stock is below $B_{trigger}$, was studied as a variant.



### HCR based on fishing mortality

In the most simple rule the TAC for the advisory year ($y+1$) is calculated as:

\begin{equation}
\widetilde{F}_{a,y+1} = \widetilde{F}_{target,y+1}\widetilde{sel}_{a,y+1}
\end{equation}

\begin{equation}
TAC_{y+1}=\sum_{a}\frac{\widetilde{F}_{a,y+1}}{\widetilde{F}_{a,y+1}+M_{a,y+1}}
\widetilde{N}_{a,y+1}\widetilde{cW}_{a,y+1}\left(1-e^{-(\widetilde{F}_{a,y+1}+M_{a,y+1})}\right) \label{eq:caltactmp}
\end{equation}

Fishing mortality rules are only based for calendar years but converted  to Icelandic Fishing year by  $C_{y/y+1}=\frac{2}{3}C_{y+1}+\frac{1}{3}C_{y}$.  The only stabilizer is $(1+x)$ up and $\frac{1}{1+x}$ down, at the moment also used below $B_{trigger}$.  


# General considerations

## Sensible inputs for observation errors

Statistically three parameters are required as in input into the observation model:

* Standard deviation, often referred to as white noise (input as here as cv)
* 1st order auto-correlation
* The long term bias

Four methods are available to estimate/emulate the value of the observation errors:

* Errors derived from the assessment model.
* Errors derived from analytical retrospective analysis.
* Errors derived from empirical retrospective analysis.
* An observation/assessment model included in the simulation framework.


The last framework, popularily referred to as "best science"/"full model" does not require specifying the above parameters as input^[It though moves the problem of proper error specification to another place in the framework, a daunting task on its own.]. In the framework often referred to as the "short cut" method, which some sarcastical termed the "fool's model" one does however need to provide the above parameters as input into the simulation framework.


### Errors derived from assessment model

This method only provides estimates of "white noise" ($cv$) but not does provide a basis to estimate auto-correlation nor bias.

Although informative, the "white noise" estimates from historical assessment models are generally considered unrealistically low to be used as a basis for assessment error in HCR evaluations.

The recent intellectual stampede within ICES towards using assessment models that aim at separating the total error term into observation error and process error creates aditional challenge when it comes to using these values as a basis of HCR-simulations.

### Errors derived from analytic retrospective analysis

For the purpose of estimating the assessment errors based on analytic retrospectives, they should preferably be run for 15-20 years for species reaching 10-15 years age. To do this requires at least 30 years of tuning data. For shorter lived species, an equivalently shorter peel could be used but only if the data input series dictates that. If the decision rule is based on population metrics in the beginning of the assessment year a conventional analysis can be used to derive an estimated value of cv, $\rho$ and bias. If the decision rule is based on future stock dynamics (advisory year and beyond), be they the ICES default F-rule or some HR-rule the analytically retrospecive analysis need include the predictions.

### Errors derived from empirical retrospective analysis

For most stocks assessed by ICES, empirical (historical) retrospecive stock summary data up to the start of the assessment year are readily available [REFERENCE]. Getting comparable data over a long time for the purpose in question is though difficult because methods to estimate historical "auxillary assessment data" such as weight and maturity at age might have changed. It is though not an impossible task to reconstruct the assessed stock-in-numbers at age from archived (ICES) reports. These data series may be of value to estimate assessment errors if the decision rule is based on the estimates in the start of the assessment year (normally only used in HR-rules). If the decision rule is base on the estimates in the start of the advisory year (like in the default ICES F-rule), the emprical reconstuction of the data need to include the historical predictions.

What compounds using empirical assessment as a basis to estimate assessment errors is that surveys used in the historical assessment series may have been short in the beginning, but become more informative as over the assessment series time. So in practice for most stocks useful empirical data series to estimate assessement errors are painfully short, although there are known exception (e.g. cod  in 5a).

## HCR type and assessment errors


The type of HCR does affect the standard deviation of the assessment error and also the bias if there is any bias. Biomass in the beginning of the assessment year is better known than biomass in the beginning of the advisory year, how much better depends on the reliably of recruitment estimates, which age-groups are included in the biomass estimate and information about growth in the assessment year. A Standard deviation of fishing mortality in the advisory year for a given TAC is then still higher, though not comparable as the relationship between fishing mortality and ratio of biomass is not linear except for relatively low values.  This amplification is taken care of by the model by projecting through the intermediate year with TAC constraint.  

Taking as an example the 2012 assessment of Icelandic haddock based on an Adapt type model tuned with the survey in March, the estimated biomass 3+ in 2012 is 106 thous. tonnes and the standard deviation of the estimate 12.5 th. tonnes or 12\%. Tac constraint of 44 thous tonnes in 2012 leads to F in 2012 of 0.47 with standard error of 0.08 or 16\% and biomass in 2013 of 85 thous. tonnes with standard deviation of 13.5 thous. tonnes or 16\%. For spawning stock the standard error as proportion of biomass are little higher or 13 and 17\%, for stock with poor recruitment estimates the uncertainty in spawning stock would be lower than in total stock. 

In assessment models for Icelandic stocks TAC in the assessment year is usually specified. Higher TAC as proportion of stock size, leads to more increase in the relative uncertainty in stock size in the advisory year. With TAC in the advisory year of 10 thous. tonnes (F=0.045), relative error of biomass of haddock in the advisory and assessment year is estimated similar. This is to be expected as most of the removals from the stock i.e natural mortality are proportional, and important factors like variability in M and prediction of growth are not included in those analysis. Taking the other extreme the estimated standard deviation of biomass in the advisory year is 24\% if 80 kt (F=1.05) are removed in 2012. 

Estimated standard error in F for a given TAC in the advisory year is considerably higher than in the assessment year. TAC of 60 thous tonnes leads to F=1.07 with standard deviation of 0.34 or 30\%. The error as proportion is lower when fishing mortality is lower. When TAC in 2013 is 30 kt estimated F is 0.4 and standard deviation 0.086 or 21\%.

In all the error estimates for the biomass in the advisory year and fishing mortality in the advisory year, uncertainty in mean weight at age is not included. How much difference it makes depends on the magnitude of the uncertainty and if there is correlation between uncertainty in estimated numbers at age and uncertainty in mean weight at age. If the correlation is positive the standard deviations are added, when there is no correlation variances are added and with negative correlation the effects cancel partly out. 

To see the effect of error in prediction of mean weight age age in the advisory year the CV of this error term for Icelandic haddock is around 10\%. CV of the estimated standard error in biomass in the advisory year is estimated around 16\% . Assuming no correlation the total CV is $\sqrt{0.16^{2}+0.1^{2}}=0.19$ or relatively small increase for substantial uncertainty in mean weight at age. 

The fishing mortality estimates shown here are based on an Adapt type model. For stocks like Icelandic haddock with large contrast in year-class size, estimate of unweighted fishing mortality tends to be noisy. Two possible improvements are to do the assessment with model where selection is parametric or using weighted F. Weighted F are not really much different from proportion of biomass based on the same selection pattern.

Uncertainty increases much faster when making predictions with specified TAC than specified harvest ratio or fishing mortality, especially if large part of the stock is removed each year. For the Icelandic haddock example CV of the spawning stock in 2015 is 16\% running with fixed fishing mortality (no error) but 34\% running with fixed TAC, both cases with relatively low fishing mortality. Here a number of important sources of uncertainty are ignored but 2015 is selected as all the age-groups contributing to the spawning stock in 2015 had been observed in 2012. 

The results shown above for Icelandic haddock are not supposed to give us the ``real'' uncertainty but rather to compare uncertainty in different values in relative sense. The most important results are. 

\begin{itemize}
\item CV of biomass in the advisory year decreases with decreased catch
in the assessment year. Factors not taken into account like stochasticity
in natural mortality and growth have more effect. 
\item CV of fishing mortality in the advisory year for a given TAC is very
high when fishing mortality is high but similar to CV in proportion
of biomass when fishing mortality is low. 
\end{itemize}
There are few important factors that need to be considered when evaluating
a HCR or at least when doing an assessment following adoption of a
HCR that leads to considerable reduction in fishing mortality. 
\begin{itemize}
\item Historical assessment becomes worse as assumptions about M have more
effect. 
\item Short term prediction improves, as larger part of the removals are
proportional and dependence on recruitment estimates is less. 
\item Auto-correlation of assessment error increases with reduced fishing
mortality. 
\item Assessment error increases if fishing mortality decreases relatively
sharply and the stock increases beyond what has been observed recently.
Assessment becomes an extrapolation. 
\end{itemize}

The evaluation of assessment error will be done separately in the
sections for each stock based on available retrospective data. A full feedback model can also be useful to test many of the above mentioned factors.  

## Sensible candidate harvest control rules

A harvest control rule (HCR) is a set of equation converting estimated (obverved) biomass ($B_{trigger}$ and in case of harvest rate rules reference biomass) and earlier advice into advised catches for the next advisory year (calendar year or fishing year).

Sensible HCR candidates depend on the dynamic characteristics of the stock in question:

* Variability in year-class size.
* Variability in stock size

In addition sensible HCR canditates depend on the accuracy of the information base available:

* Quality of assessment of the adult part of the stock. 
* Quality of recruitment estimates
* Quality in survey data
* Availability of maturity data??.
* Co-ocurrence of recruits and adult part of the stock in the fisheries.

In addition one has:

* Mixed fisheries issues.
* Econmics of the fisheries.

How these characteristics affect the type of HCR:

* With large variability in year-class size care must be taken to increase TAC when large year-class is entering the fishery, except the fisheries are really targeting this year-class as much as older year-classes. 
* Large/rapid true variations in stock size make catch stabilizers questionable.
* Large ``high frequency'' assessment error makes use of catch stabilizers suitable as too much unnecessary inter-annual variability in advice undermines the HCR.
* Poor recruitment estimates favour decision rules based on the part of the biomass that recruitment estimates do not affect too much.
* With good recruitment estimates, rule looking few years ahead are a possibility.
* For stock with large variations in mean weight at age the reference biomass or reference fishing mortality should in many cases be based on size rather than age. This applies specially to stocks where selection
is more size than age based.
* With good survey data weights at age in the survey are more appropriate values than for calculations of reference biomass than values from catches. One problem with values from catches is that they overestimate
the contributions of the youngest age groups where the fisheries only target the largest individuals. 
* Same applies to maturity at age data that survey data are more appropriate values than catch values if survey is conducted in a season where maturity stage is easily identified. Here the problem of getting representative
values for the stock is even larger than with weights at age as fisheries are often targeting the mature part of the stock in the season when maturity at age is easiest to detect. Getting ungutted fish from landings, required for registration of maturity stage is also a problem in many fisheries. How maturity is defined can affect trends in spawning stock but maturity from catches tend to overestimate the contribution from young fish and therefore overestimate spawning potential when mortality has been high.

# Setting up assessment and simulations



# Older text, possibly to be recycled

Three parameters are required for the AR model, bias, 1st order auto-correlation
and standard deviation. If a bias is suspected it is treated separately
by increasing the harvest ratio/fishing mortality by the bias. Even 
relatively small bias or 5-10\%
can have considerable effect on the performance of the HCR. Large
auto-correlation can also lead to increased risk of spawning stock going
below $B_{lim}$ except harvest ratio is very low. What is large auto-correlation
depends on the longevity of the species, for long lived species with
low mortality number of years with poor recruitment will not cause
major problem. 



All type of Harvest control rules are tested with and without a trigger.
A final approved HCR must have trigger action but during testing behaviour
of the HCR was investigated without a trigger. Two types of possible
trigger action were tested, the first one the traditional one where
the harvest ratio is reduced by the fraction $\frac{SSB}{SSB_{trigger}}$
where SSB refers either to spawning stock either in the advisory year,
or the assessment year. This type of trigger is referred to as as
$Trigger_{1}$ in what follows. 

The second type of trigger rule is based on the fact that year-class
size of haddock is reasonably well known at age 1 so the spawning
stock can be predicted 4 years ahead and action taken if poor recruitment
has been seen. The rule is set up in the following way. Predict
spawning stock 4 years ahead and if the spawning stock is predicted
to be below $B_{lim}$ with more than 5\% probability the Harvest
ratio is reduced as required but not more than to 2/3 of the base
harvest ratio. If the SSB is below $SSB_{trigger}$ the base harvest
ratio is multiplied by the ratio $\frac{SSB}{B_{trigger}}$ and the
minimum harvest ratio is still 2/3 of the base harvest ratio. This
type of trigger is referred to as $Trigger_{2}$ in what follows. 

Catch stabilizers tested were to let current fishing years advice
have 50\% weight in the advice for the next fishing year. 

....

That $F_{target}$ is a function of $\widetilde{SSB}$ not $SSB$ is important and leads to rules with trigger action being problematic due to to much variability in catches. Case to look at Norwegian spring spawning herring at the moment

Three parameters are required for the AR model, bias, 1st order auto-correlation
and standard deviation. If a bias is suspected it is treated separately
by increasing the harvest ratio/fishing mortality by the bias. Even 
relatively small bias or 5-10\%
can have considerable effect on the performance of the HCR. Large
auto-correlation can also lead to increased risk of spawning stock going
below $B_{lim}$ except harvest ratio is very low. What is large auto-correlation
depends on the longevity of the species, for long lived species with
low mortality number of years with poor recruitment will not cause
major problem. 




## More stuff


The model is all written in AD-model builder but is divided in different
sub-models (figure 1). First the historical assessment model is run,
estimating biological parameters and selection pattern of the fisheries
with confidence intervals on parameters, stock size and fishing mortality
calculated from the inverse Hessian matrix. The inverse Hessian matrix
is then used as proposal distribution in MCMC simulations where the
number of simulations are 2 millions and the parameters from every
1000th run saved to a file. (done with the command ashcatage -nox
-mcmc 2000000 -mcscale -mcsave 1000). The saved sets of parameters
are then used in 2000 stochastic runs, in each run the assessment
model is run, feeding directly into the prognosis, observation model
and Harvest Control rule that in the program are just simple functions
in the prognosis function. The stochastic simulations are done with
the command ashcatage -mceval which reads the file ashcatage.psv storing
the 2000 sets of parameter values stored in the mcmc run. The model
is written in such a way that it must do prediction for at least 4
years, even in the estimation mode. In the stochastic simulation mode
the numbers of years simulated is usually increased from around 5 to
50-100 but running the estimation with 50 years will increase the
computation time as each mcmc evaluation involves 2 million function
evaluations. In the estimation phase non-differential functions are not
allowed, and stochasticity in biological parameters is not allowed,
at least not in values that affect the ``likelihood function''.
In Admodel builder code the stochastic simulation phase is identified
as {mc\_eval\_phase} and some functions are only active in this phase
(checked in code with {if(mc\_eval\_phase())}







\subsection{Prediction}

The prediction occurs in few steps. 
\begin{enumerate}
\item Calculate mean weight and maturity at age (stochastic). 
\item Calculate selection at age. 
\item Calculate the assessment error. 
\item Calculate recruitment residuals. 
\item Multiply the stock in the beginning of the assessment year by
  the assessment error getting estimated stock.  
\item Projecting the estimated stock one year forward with the TAC
  obtained from last years assessment use catch weights from the year 
  before the assessment year ($wC_{y-1}$.  
\item Calculate the estimated spawning stock in the beginning of the advisory
  year (year after the assessment year) $SSB_{pred,y+1}$ based on
  estimated stock numbers , and
  weight and maturity at age the year before the assessment year.
  (assuming that the weight prediction is just use last weights
  unchanged, could of course implement average of last 3 years.  
\item Calculate $F_{target}$ based on $SSB_{pred,y+1}$
\item Calculate catch in the advisory year based on estimated numbers
  in the beginning of the advisory year, catch weights in the the year
  before the assessment year ($wC_{y-1}$) and $F_{target}$.  
\item The ``real stock'' is then projected forward base on the ``real
  weights at age'' and the TAC from last year.  
\end{enumerate}

An important point here is that the projection each year is done by a
TAC constraint, where the TAC is generated by estimated stock size
one year earlier.  This leads to increase in uncertainty compared to
uncertainty in stock size in the beginning of the assessment year.  


Some harvest control rules are based on ``future stock size'', in
those cases steps 5-10 need to be performed iteratively. 

Mean weight at age, maturity at age, recruitment , selection at age
and maturity at age can be multiplied with stochastic noise, generated
as a first order AR model. For Icelandic saithe and haddock stochastic
variability in maturity was not included as discussed separately for
each species. 




\subsection{Fisheries model. }

The fisheries model transfers the advice, that is the output from
the HCR into removals from the stock. This model could include black
landings and discards but in the simulations done here the fisheries
model is nothing more than converting catch to removals by age using
equations \ref{catcheq:1}to\ref{catcheq:3} and \ref{catcheq:5},
in reverse mode as the total yield, stock in numbers, selection pattern
and stock weights are known but fishing mortality unknown. The solution
is small minimization routine in the model using Newtons ore bisection method and
numerical differentiation, only one parameter is estimated. 

Stochasticity in selection is modeled for haddock but not saithe.
Sensitivity to different selection patterns is tested for saithe. 




\subsection{Risk criterion}

At the time of this writing (March 2013 updated April 2016)  it is 
not clear what minimum risk criterion
ICES will use with respect to evaluating HCRs relative to the precautionary
approach. Currently three criterion have in practice been used:
\begin{itemize}
\item A: Risk of going below some biomass criterion during a single specified
future year.
\item B: Maximum risk in any one year of going below some biomass criterion
over a specified future periods of years.
\item C: Risk of going below some biomass criterion at least once over a
specified future period of years.
\end{itemize}


